name: ascend_ultimate_env
channels:
  - defaults
  - conda-forge
  - anaconda
  - nvidia
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow=2.12.0
  - tensorflow-gpu=2.12.0
  - tensorflow-datasets
  - tensorflow-quantum
  - tensorflow-io
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8
  - jax=0.4.13
  - jaxlib=0.4.13
  - keras=2.12.0
  - onnx=1.14.0
  - onnxruntime=1.15.1
  - onnxruntime-gpu=1.15.1
  - mxnet=1.9.1
  - mindspore=2.2.0
  - deepspeed=0.9.2
  - pytorch-lightning=2.0.4
  - accelerate=0.22.0
  - transformers=4.30.2
  - sentence-transformers=2.2.2
  - datasets=2.14.5
  - spacy=3.6.0
  - stanza=1.6.1
  - nltk=3.8.1
  - langchain=0.0.293
  - tiktoken=0.4.0
  - openai=0.28.1
  - gpt4all=2.4.1
  - opencv=4.8.1
  - pillow=10.0.1
  - scikit-image=0.21.0
  - dlib=19.24.2
  - yolov5=7.0.0
  - mmdetection=3.2.0
  - deepface=0.0.79
  - face-recognition=1.3.0
  - stable-diffusion=2.1.0
  - clip-by-openai=0.3.0
  - stable-baselines3=2.0.0
  - rllib=2.6.0
  - gymnasium=0.29.0
  - autogpt=0.5.1
  - crewai=0.3.2
  - babyagi=1.2.0
  - angr=9.3.4
  - frida=16.0.3
  - unicorn=2.0.0
  - z3-solver=4.12.2
  - volatility3=2.4.0
  - stealthcrypto=0.4.5
  - pefile=2023.2.7
  - radare2=5.7.2
  - qiskit=0.44.0
  - pennylane=0.32.0
  - cirq=1.1.0
  - pyquil=3.1.0
  - braket=1.21.0
  - azure-quantum=0.20.0
  - pytorch-quantum
  - tequila
  - quantumrandom
  - qkd
  - quantum_crypto
  - xgboost=1.7.6
  - lightgbm=3.3.5
  - alpaca-trade-api=2.3.0
  - binance=1.0.17
  - quantlib=1.30
  - web3=6.3.0
  - ray=2.5.0
  - dask=2023.7.1
  - joblib=1.3.2
  - pyspark=3.5.0
  - mpi4py=3.1.4
  - automl=0.10.0
  - auto-sklearn=0.16.0
  - auto-keras=1.1.0
  - tpot=0.12.0
  - h2o=3.40.0.2
  - firecracker=1.2.3
  - qemu=7.2.0
  - docker-py=6.1.3
  - pysec=1.0.4
  - secure-execution=0.5.0
  - streamlit=1.28.0
  - dash=2.14.0
  - gradio=3.36.1
  - panel=1.2.2
  - voila=0.4.0
  - flask=2.2.5
  - fastapi=0.110.0
  - brownie=1.22.0
  - solidity-compiler=1.6.0
  - hyperledger=1.5.0
  - whisper=1.1.0
  - speechrecognition=3.10.0
  - pyttsx3=2.91
  - tts=0.8.3
  - starcoder=0.4.1
  - codex=1.1.0
  - codet5=1.0.3
  - polycoder=1.2.2
  - gpt-engineer=0.3.0
  - google-cloud-ai=2.13.1
  - awscli=1.29.19
  - azure-ai=3.1.0
  - selenium=4.11.2
  - scrapy=2.10.0
  - beautifulsoup4=4.12.2
  - requests=2.31.0
  - mechanize=0.4.9
  - tqdm=4.66.1
  - psutil=5.9.5
  - cudnn=8.8.0
  - tensorflow-probability=0.21.0
  - tensorboard=2.12.0
  - multiprocess
  - soundfile
  - pydantic
  - zerorpc
  - aiomultiprocessing
  - flask-cors
  - pip:
      - frida
      - capstone
      - keystone-engine
      - unicorn
      - pyelftools
      - angr
      - z3-solver
      - r2pipe
      - lief
      - miasm
      - volatility3
      - pefile
      - hexdump
      - python-iptables
      - pywinauto
      - pydbg
      - pwntools
      - ropgadget
      - ropper
      - avatar2
      - pyvex
      - shellphish-qemu
      - smda
      - ghidra_bridge
      - pytun
      - impacket
      - kamene
      - dnsrecon
      - mitmproxy
      - evilginx2
      - cobaltstrike
      - metasm
      - dnslib
      - pypykatz
      - passlib
      - binwalk
      - firmadyne
      - gdbgui
      - fireeye-flare-ida
      - yara
      - yara-python
      - pyfrida
      - xortool
      - stegcracker
      - stegpy
      - pypx
      - rpyc
      - pyhidapi
      - psychopy
      - pyserial
      - pyftdi
      - pyvisa
      - sigrok-cli
      - sigrokdecode
      - libusb1
      - usbmuxd
      - openstego
      - cryptoauthlib
      - sgp4
      - pwnlib
      - pysnmp
      - faker
      - rich
      - termcolor
      - coloredlogs
      - loguru
      - typer
      - git+https://github.com/bigcode-project/starcoder.git
      - git+https://github.com/Salesforce/codet5.git
      - git+https://github.com/Significant-Gravitas/AutoGPT.git
      - git+https://github.com/jacobmarks/whisper-mic.git