channels:
- nvidia
- conda-forge
- defaults
- anaconda
dependencies:
- python=3.9
- pip
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- scikit-learn
- tensorflow=2.12.0
- tensorflow-gpu=2.12.0
- tensorflow-datasets
- tensorflow-quantum
- tensorflow-io
- pytorch=2.0.1
- torchvision=0.15.2
- torchaudio=2.0.2
- cudatoolkit=11.8
- jax=0.4.13
- jaxlib=0.4.13
- keras=2.12.0
- onnx=1.14.0
- onnxruntime=1.15.1
- onnxruntime-gpu=1.15.1
- mxnet=1.9.1
- mindspore=2.2.0
- deepspeed=0.9.2
- pytorch-lightning=2.0.4
- accelerate=0.22.0
- transformers=4.30.2
- sentence-transformers=2.2.2
- datasets=2.14.5
- spacy=3.6.0
- stanza=1.6.1
- nltk=3.8.1
- langchain=0.0.293
- tiktoken=0.4.0
- openai=0.28.1
- gpt4all=2.4.1
- opencv=4.8.1
- pillow=10.0.1
- scikit-image=0.21.0
- dlib=19.24.2
- yolov5=7.0.0
- mmdetection=3.2.0
- deepface=0.0.79
- face-recognition=1.3.0
- stable-diffusion=2.1.0
- clip-by-openai=0.3.0
- stable-baselines3=2.0.0
- rllib=2.6.0
- gymnasium=0.29.0
- autogpt=0.5.1
- crewai=0.3.2
- babyagi=1.2.0
- angr=9.3.4
- frida=16.0.3
- unicorn=2.0.0
- z3-solver=4.12.2
- volatility3=2.4.0
- stealthcrypto=0.4.5
- pefile=2023.2.7
- radare2=5.7.2
- qiskit=0.44.0
- pennylane=0.32.0
- cirq=1.1.0
- pyquil=3.1.0
- braket=1.21.0
- azure-quantum=0.20.0
- pytorch-quantum
- tequila
- quantumrandom
- qkd
- quantum_crypto
- xgboost=1.7.6
- lightgbm=3.3.5
- alpaca-trade-api=2.3.0
- binance=1.0.17
- quantlib=1.30
- web3=6.3.0
- ray=2.5.0
- dask=2023.7.1
- joblib=1.3.2
- pyspark=3.5.0
- mpi4py=3.1.4
- automl=0.10.0
- auto-sklearn=0.16.0
- auto-keras=1.1.0
- tpot=0.12.0
- h2o=3.40.0.2
- firecracker=1.2.3
- qemu=7.2.0
- docker-py=6.1.3
- pysec=1.0.4
- secure-execution=0.5.0
- streamlit=1.28.0
- dash=2.14.0
- gradio=3.36.1
- panel=1.2.2
- voila=0.4.0
- flask=2.2.5
- fastapi=0.110.0
- brownie=1.22.0
- solidity-compiler=1.6.0
- hyperledger=1.5.0
- whisper=1.1.0
- speechrecognition=3.10.0
- pyttsx3=2.91
- tts=0.8.3
- starcoder=0.4.1
- codex=1.1.0
- codet5=1.0.3
- polycoder=1.2.2
- gpt-engineer=0.3.0
- google-cloud-ai=2.13.1
- awscli=1.29.19
- azure-ai=3.1.0
- selenium=4.11.2
- scrapy=2.10.0
- beautifulsoup4=4.12.2
- requests=2.31.0
- mechanize=0.4.9
- tqdm=4.66.1
- psutil=5.9.5
- cudnn=8.8.0
- tensorflow-probability=0.21.0
- tensorboard=2.12.0
- multiprocess
- soundfile
- pydantic
- zerorpc
- aiomultiprocessing
- flask-cors
- pefile==2021.5.24
- pyquil==3.0.0
- z3==4.8.9.0
- torch-audiomentations
- pypng
- git+https://github.com/Salesforce/codet5.git
- secrets
- yfinance
- alpaca_trade_api==2.0.0
- torchvision=0.11.1
- stealthcrypto==0.4.0
- pyasn1-modules
- future
- dash-table
- jsonschema
- websockets
- entrypoints
- bson
- weakref
- obfuscation
- torchaudio=0.10.0
- bluetooth_hijack
- contextlib
- psutil
- cirq==0.13.0
- spacy
- ccxt
- randomname
- pyautogui
- pennylane
- cryptography.fernet
- azure-quantum
- win32api
- cryptography.hazmat.primitives.ciphers
- newspaper
- requests-html
- transformers
- pytorch==1.10.0
- voice_cloning
- huggingface-hub
- terminado
- fonttools
- pytorch_scatter
- pefile
- protobuf
- docx
- quantlib==1.18
- pickle
- accelerate
- web3
- lxml
- beautifulsoup4==4.10.0
- scrapy==2.5.0
- scrapy
- tabulate
- win32security
- s3transfer
- cffi
- scrypt
- tensorflow=2.6.0
- keyring
- idalink
- backcall
- hashlib==3.2
- async-timeout
- unicorn==1.0.2
- ipywidgets
- pycryptodome==3.10.1
- quantlib
- google-cloud-storage
- chardet
- soupsieve
- tensorflow==2.6.0
- wave
- pyzbar
- pytorch=1.10.0
- google-auth
- tensorflow
- dns.resolver
- stochastic
- pyttsx3
- quantum_evolve
- darkbank
- pycparser
- web3==5.28.0
- firebase-admin
- jwt
- process_cloak
- pyyaml
- dill
- aiosignal
- yaml
- mdit-py-plugins
- GPUtil
- memory-profiler
- pymongo
- radare2
- python-dotenv
- pyjwt
- selenium.webdriver.chrome.options
- pytz
- pydasm
- ray==1.5.0
- bytecode_forge
- newspaper3k
- scapy.all
- torch-sparse
- scipy.optimize
- nacl
- pot
- requests==2.26.0
- capstone
- selenium.webdriver.support.ui
- tiktoken
- starlette
- passlib
- azure-identity
- pandocfilters
- secp256k1
- pyelliptic
- retrying
- pennylane==0.16.0
- pyasn1
- slack-sdk
- pypdf2
- auto-patcher
- torch-geometric
- xgboost
- braket.aws==1.1.1
- murmurhash
- keystone
- zope.interface
- python-json-logger
- qrcode
- zerotrace
- bs4
- networkx
- cryptography==3.4.8
- importlib-resources
- antimemdetect
- swarm_ai
- memory_hijack
- google-pasta
- speech_recognition
- avro
- parso
- openpyxl
- cmake
- blockchain
- hashlib
- auto-py-to-exe
- pytesseract==0.3.8
- googleapiclient
- gunicorn
- irs_hacker
- shutil
- jupyter
- beautifulsoup4
- i2p
- uvicorn
- sklearn.cluster
- socks
- dask==2021.11.0
- inspect
- redis
- geopy
- ecdsa
- cython
- self_evolve
- et-xmlfile
- fastavro
- angr==9.3.4
- qiskit==0.32.1
- decorator
- python-barcode
- mdurl
- OpenSSL
- multiprocessing
- statsmodels
- security_onion
- pycountry
- fsspec
- xmltodict
- webencodings
- braket.aws
- qiskit=0.32.1
- ipykernel
- torch-spline-conv
- threading
- albumentations
- sentence-transformers
- paramiko
- deepface
- google-auth-oauthlib
- mistune
- tqdm
- plotly.graph_objects
- kiwisolver
- shadow_remittance==0.1.5
- asyncio
- binance.client
- jmespath
- thinc
- twilio
- joblib==1.0.1
- email-validator
- opencv-python
- openai
- braket
- email
- post_quantum==0.3.0
- cycler
- tensorboard-data-server
- binance
- boto3
- oscrypto
- cryptography.hazmat.backends
- pytorch-lightning
- dotmap
- backoff
- prometheus-client
- angr
- discord
- flask
- scapy
- validators
- torch
- gitpython
- rsa
- shadow_remittance
- pygetwindow
- transformers=4.15.0
- stem.control
- google-cloud
- quimb
- scikit-image
- binance==1.0.15
- scipy.stats
- honeybot
- auto-news
- spooftool
- platformdirs
- pybloom-live
- deepfake
- pyimsl
- bcrypt
- dash-bootstrap-components
- flask-sqlalchemy
- jupyterlab-widgets
- toml
- importlib
- emu8086==4.0.2
- host_redirection
- z3-solver
- shadow_money==0.2.1
- frida
- pytorch_geometric
- selenium.webdriver.common.by
- ffmpeg
- pyquil
- dash
- pytesseract
- flatbuffers
- anti-forensics
- yfinance==0.1.63
- wandb
- brotli
- lief
- distributed
- idalink==2.5.4
- hmac
- qiskit.providers.aer
- moviepy.editor
- sqlalchemy
- joblib
- pybind11
- shadow_money
- git+https://github.com/bigcode-project/starcoder.git
- grpcio
- defi_framework==0.3.2
- defusedxml
- azure-quantum==0.16.0
- selenium.webdriver.chrome.service
- smtplib
- pyautogui==0.9.53
- network_obfuscator
- python-dateutil
- boto
- opt-einsum
- google-cloud-firestore
- libnacl
- mechanize
- pandas==1.2.5
- omegaconf
- steganography
- numpy==1.19.5
- sentencepiece
- absl-py
- pyfingerprint
- awscli
- ray
- msgpack
- sympy
- pytorch_spline_conv
- pymupdf
- safetensors
- idna
- speech_recognition==3.8.1
- packaging
- screeninfo
- cryptography
- colorama
- selenium-stealth
- torchvision==0.11.1
- spacy-lookups-data
- ptyprocess
- torchvision
- six
- cloudscraper
- stegano
- fake_useragent
- moviepy
- keras-preprocessing
- massmind
- feedparser
- stem
- jina2
- frida==15.1.0
- certifi
- fastparquet
- unicorn
- struct
- kornia
- keyboard==0.13.5
- zmq.asyncio
- contextlib2
- imageio
- gnupg
- llvmlite
- tradewolf
- cryptography.hazmat.primitives.asymmetric
- json5
- altair
- taxshield
- selenium
- selenium.webdriver.support
- urllib3
- cryptography.hazmat.primitives.kdf.pbkdf2
- oauthlib
- uuid
- cudatoolkit==11.1
- gast
- transformers==4.15.0
- requests-oauthlib
- filelock
- z3
- speechrecognition
- yacs
- tweepy
- torchaudio==0.10.0
- scikit-learn==0.24.2
- emu8086
- commonmark
- argon2-cffi
- srsly
- cirq
- uuid==1.30
- pkgutil
- pdfkit
- pyttsx3==2.90
- tensorboard
- qiskit.algorithms
- pyparsing
- alpaca-trade-api
- pytorch3d
- pyaudio==0.2.11
- dash-core-components
- yarl
- wrapt
- timm
- torpy
- string
- hyperstealth
- stealthcrypto
- qsharp
- selenium==4.0.0
- zmq
- facebook_scraper
- numba
- crypto_blender
- tifffile
- datasets
- tzdata
- keras
- usb_persistence
- python-magic
- pyims
- markdown
- opencv
- babel
- host_shield
- biopython
- pysnmp
- tensorflow-estimator
- dask
- importlib-metadata
- gpt_troller
- dash-html-components
- platform
- threadpoolctl
- tornado
- mamba
- pytorch_sparse
- bleach
- msword
- ccxt==1.63.46
- pycryptodome
- email.mime.text
- qiskit
- torchaudio
- pylatexenc
- configparser
- volatility3
- defi_framework
- editdistance
- barcode
- dns-lexicon
- tensorboard-plugin-wit
- post_quantum
- qiskit_ibm_runtime
- librosa
- vuln_scanner
- pyaudio
- cudatoolkit=11.1
- cachetools
- torch-scatter
- requests
- torch-tb-profiler
- zkpy
- regex
- qiskit_machine_learning.algorithms
- lazy_loader
- werkzeug
- lxml==4.6.3
- cloudpickle
- fastapi
- audioread
- avro-python3
- clipboard
- jedi
- matplotlib==3.3.4
- stable-baselines3
- pywavelets
- h5py
- dark_web_exchanger
- plotly
- python-slugify
- aiohttp
- signal
- prompt-toolkit
- cryptography.hazmat.primitives.hashes
- math
- pillow
- orjson
- termcolor
- tokenizers
- pyzbar.pyzbar
- pip:
  - rich
  - keystone-engine
  - typer
  - pyfrida
  - rpyc
  - pefile
  - sigrokdecode
  - usbmuxd
  - binwalk
  - pwnlib
  - hexdump
  - git+https://github.com/Significant-Gravitas/AutoGPT.git
  - metasm
  - python-iptables
  - ropgadget
  - pydbg
  - unicorn
  - pyvex
  - ghidra_bridge
  - passlib
  - yara-python
  - xortool
  - psychopy
  - sgp4
  - pysnmp
  - smda
  - coloredlogs
  - avatar2
  - dnsrecon
  - lief
  - pypykatz
  - sigrok-cli
  - openstego
  - pwntools
  - gdbgui
  - pytun
  - pyhidapi
  - evilginx2
  - capstone
  - volatility3
  - kamene
  - impacket
  - yara
  - r2pipe
  - loguru
  - dnslib
  - cryptoauthlib
  - stegcracker
  - pyserial
  - frida
  - faker
  - git+https://github.com/bigcode-project/starcoder.git
  - pyelftools
  - shellphish-qemu
  - ropper
  - libusb1
  - cobaltstrike
  - fireeye-flare-ida
  - stegpy
  - termcolor
  - pypx
  - pyvisa
  - pyftdi
  - z3-solver
  - firmadyne
  - pywinauto
  - mitmproxy
  - angr
  - git+https://github.com/Salesforce/codet5.git
  - miasm
  - git+https://github.com/jacobmarks/whisper-mic.git
name: ascend_ultimate_env
