name: gremlin_workflow
entrypoint: process
nodes:
  - id: process
    type: agent
    handler: agents.gremlin_agent.GremlinAgent
    config:
      name: Gremlin
      tools:
        - scrape_web
        - query_api
        - buy_crypto
        - fetch_logs
        - self_edit
        - instance_orchestrator