channels:
- defaults
- conda-forge
- anaconda
- nvidia
dependencies:
- GPUtil
- OpenSSL
- absl-py
- accelerate
- aiohttp
- aiosignal
- albumentations
- alpaca-trade-api
- alpaca_trade_api==2.0.0
- altair
- angr
- angr==9.3.4
- anti-forensics
- antimemdetect
- argon2-cffi
- async-timeout
- asyncio
- audioread
- auto-news
- auto-patcher
- auto-py-to-exe
- avro
- avro-python3
- awscli
- azure-identity
- azure-quantum
- azure-quantum==0.16.0
- babel
- backcall
- backoff
- barcode
- bcrypt
- beautifulsoup4
- beautifulsoup4==4.10.0
- binance
- binance.client
- binance==1.0.15
- biopython
- bleach
- blockchain
- bluetooth_hijack
- boto
- boto3
- braket
- braket.aws
- braket.aws==1.1.1
- brotli
- bs4
- bson
- bytecode_forge
- cachetools
- capstone
- ccxt
- ccxt==1.63.46
- certifi
- cffi
- chardet
- cirq
- cirq==0.13.0
- clipboard
- cloudpickle
- cloudscraper
- cmake
- colorama
- commonmark
- configparser
- contextlib
- contextlib2
- crypto_blender
- cryptography
- cryptography.fernet
- cryptography.hazmat.backends
- cryptography.hazmat.primitives.asymmetric
- cryptography.hazmat.primitives.ciphers
- cryptography.hazmat.primitives.hashes
- cryptography.hazmat.primitives.kdf.pbkdf2
- cryptography==3.4.8
- cudatoolkit=11.1
- cudatoolkit==11.1
- cycler
- cython
- dark_web_exchanger
- darkbank
- dash
- dash-bootstrap-components
- dash-core-components
- dash-html-components
- dash-table
- dask
- dask==2021.11.0
- datasets
- decorator
- deepface
- deepfake
- defi_framework
- defi_framework==0.3.2
- defusedxml
- dill
- discord
- distributed
- dns-lexicon
- dns.resolver
- docx
- dotmap
- ecdsa
- editdistance
- email
- email-validator
- email.mime.text
- emu8086
- emu8086==4.0.2
- entrypoints
- et-xmlfile
- facebook_scraper
- fake_useragent
- fastapi
- fastavro
- fastparquet
- feedparser
- ffmpeg
- filelock
- firebase-admin
- flask
- flask-cors
- flask-sqlalchemy
- flatbuffers
- fonttools
- frida
- frida==15.1.0
- fsspec
- future
- gast
- geopy
- git+https://github.com/Salesforce/codet5.git
- git+https://github.com/bigcode-project/starcoder.git
- gitpython
- gnupg
- google-auth
- google-auth-oauthlib
- google-cloud
- google-cloud-firestore
- google-cloud-storage
- google-pasta
- googleapiclient
- gpt_troller
- grpcio
- gunicorn
- h5py
- hashlib
- hashlib==3.2
- hmac
- honeybot
- host_redirection
- host_shield
- huggingface-hub
- hyperstealth
- i2p
- idalink
- idalink==2.5.4
- idna
- imageio
- importlib
- importlib-metadata
- importlib-resources
- inspect
- ipykernel
- ipywidgets
- irs_hacker
- jedi
- jina2
- jmespath
- joblib
- joblib==1.0.1
- json5
- jsonschema
- jupyter
- jupyterlab-widgets
- jwt
- keras
- keras-preprocessing
- keyboard==0.13.5
- keyring
- keystone
- kiwisolver
- kornia
- lazy_loader
- libnacl
- librosa
- lief
- llvmlite
- lxml
- lxml==4.6.3
- mamba
- markdown
- massmind
- math
- matplotlib
- matplotlib==3.3.4
- mdit-py-plugins
- mdurl
- mechanize
- memory-profiler
- memory_hijack
- mistune
- moviepy
- moviepy.editor
- msgpack
- msword
- multiprocess
- multiprocessing
- murmurhash
- nacl
- network_obfuscator
- networkx
- newspaper
- newspaper3k
- numba
- numpy
- numpy==1.19.5
- oauthlib
- obfuscation
- omegaconf
- openai
- opencv
- opencv-python
- openpyxl
- opt-einsum
- orjson
- oscrypto
- packaging
- pandas
- pandas==1.2.5
- pandocfilters
- paramiko
- parso
- passlib
- pdfkit
- pefile
- pefile==2021.5.24
- pennylane
- pennylane==0.16.0
- pickle
- pillow
- pip
- pkgutil
- platform
- platformdirs
- plotly
- plotly.graph_objects
- post_quantum
- post_quantum==0.3.0
- pot
- process_cloak
- prometheus-client
- prompt-toolkit
- protobuf
- psutil
- ptyprocess
- pyasn1
- pyasn1-modules
- pyaudio
- pyaudio==0.2.11
- pyautogui
- pyautogui==0.9.53
- pybind11
- pybloom-live
- pycountry
- pycparser
- pycryptodome
- pycryptodome==3.10.1
- pydantic
- pydasm
- pyelliptic
- pyfingerprint
- pygetwindow
- pyims
- pyimsl
- pyjwt
- pylatexenc
- pymongo
- pymupdf
- pyparsing
- pypdf2
- pypng
- pyquil
- pyquil==3.0.0
- pysnmp
- pytesseract
- pytesseract==0.3.8
- python-barcode
- python-dateutil
- python-dotenv
- python-json-logger
- python-magic
- python-slugify
- python=3.9
- pytorch-lightning
- pytorch-quantum
- pytorch3d
- pytorch=1.10.0
- pytorch==1.10.0
- pytorch_geometric
- pytorch_scatter
- pytorch_sparse
- pytorch_spline_conv
- pyttsx3
- pyttsx3==2.90
- pytz
- pywavelets
- pyyaml
- pyzbar
- pyzbar.pyzbar
- qiskit
- qiskit.algorithms
- qiskit.providers.aer
- qiskit=0.32.1
- qiskit==0.32.1
- qiskit_ibm_runtime
- qiskit_machine_learning.algorithms
- qkd
- qrcode
- qsharp
- quantlib
- quantlib==1.18
- quantum_crypto
- quantum_evolve
- quantumrandom
- quimb
- radare2
- randomname
- ray
- ray==1.5.0
- redis
- regex
- requests
- requests-html
- requests-oauthlib
- requests==2.26.0
- retrying
- rsa
- s3transfer
- safetensors
- scapy
- scapy.all
- scikit-image
- scikit-learn
- scikit-learn==0.24.2
- scipy
- scipy.optimize
- scipy.stats
- scrapy
- scrapy==2.5.0
- screeninfo
- scrypt
- secp256k1
- secrets
- security_onion
- selenium
- selenium-stealth
- selenium.webdriver.chrome.options
- selenium.webdriver.chrome.service
- selenium.webdriver.common.by
- selenium.webdriver.support
- selenium.webdriver.support.ui
- selenium==4.0.0
- self_evolve
- sentence-transformers
- sentencepiece
- shadow_money
- shadow_money==0.2.1
- shadow_remittance
- shadow_remittance==0.1.5
- shutil
- signal
- six
- sklearn.cluster
- slack-sdk
- smtplib
- socks
- soundfile
- soupsieve
- spacy
- spacy-lookups-data
- speech_recognition
- speech_recognition==3.8.1
- speechrecognition
- spooftool
- sqlalchemy
- srsly
- stable-baselines3
- starlette
- statsmodels
- stealthcrypto
- stealthcrypto==0.4.0
- stegano
- steganography
- stem
- stem.control
- stochastic
- string
- struct
- swarm_ai
- sympy
- tabulate
- taxshield
- tensorboard
- tensorboard-data-server
- tensorboard-plugin-wit
- tensorflow
- tensorflow-datasets
- tensorflow-estimator
- tensorflow-io
- tensorflow-quantum
- tensorflow=2.6.0
- tensorflow==2.6.0
- tequila
- termcolor
- terminado
- thinc
- threading
- threadpoolctl
- tifffile
- tiktoken
- timm
- tokenizers
- toml
- torch
- torch-audiomentations
- torch-geometric
- torch-scatter
- torch-sparse
- torch-spline-conv
- torch-tb-profiler
- torchaudio
- torchaudio=0.10.0
- torchaudio==0.10.0
- torchvision
- torchvision=0.11.1
- torchvision==0.11.1
- tornado
- torpy
- tqdm
- tradewolf
- transformers
- transformers=4.15.0
- transformers==4.15.0
- tweepy
- twilio
- tzdata
- unicorn
- unicorn==1.0.2
- urllib3
- usb_persistence
- uuid
- uuid==1.30
- uvicorn
- validators
- voice_cloning
- volatility3
- vuln_scanner
- wandb
- wave
- weakref
- web3
- web3==5.28.0
- webencodings
- websockets
- werkzeug
- win32api
- win32security
- wrapt
- xgboost
- xmltodict
- yacs
- yaml
- yarl
- yfinance
- yfinance==0.1.63
- z3
- z3-solver
- z3==4.8.9.0
- zerotrace
- zkpy
- zmq
- zmq.asyncio
- zope.interface
name: ascend_final_env
