[core]
workspace_base = "./workspace"
persist_sandbox = false
run_as_devin = true
sandbox_container_image = "custom_image"

[llm]
api_key = ""
base_url = "http://localhost:5000"
model = "Mistral-7B-Instruct"
temperature = 0.1
max_input_tokens = 4000
max_output_tokens = 4000
