system:
  name: AscendAI
  mode: production
  logging_level: DEBUG
  heartbeat_interval: 30  # in seconds
  enable_mutation_engine: true
  max_memory_allocation: 8192  # in MB

features:
  self_healing: true
  synthetic_identity_emulation: true
  stealth_mode: false

paths:
  log_dir: /mnt/SkylineX/AscendAI/Ascend_Core/data/logs/
  data_input: /mnt/SkylineX/AscendAI/Ascend_Core/data/inputs/
  data_output: /mnt/SkylineX/AscendAI/Ascend_Core/data/outputs/