channels:
- defaults
- conda-forge
dependencies:
- multiprocess
- pefile==2021.5.24
- pyquil==3.0.0
- z3==4.8.9.0
- torch-audiomentations
- pypng
- git+https://github.com/Salesforce/codet5.git
- secrets
- yfinance
- alpaca_trade_api==2.0.0
- torchvision=0.11.1
- tensorflow-datasets
- stealthcrypto==0.4.0
- pyasn1-modules
- future
- dash-table
- jsonschema
- websockets
- entrypoints
- bson
- weakref
- obfuscation
- torchaudio=0.10.0
- pytorch-quantum
- tequila
- bluetooth_hijack
- contextlib
- psutil
- cirq==0.13.0
- quantumrandom
- spacy
- ccxt
- randomname
- pyautogui
- pennylane
- cryptography.fernet
- azure-quantum
- win32api
- cryptography.hazmat.primitives.ciphers
- newspaper
- requests-html
- transformers
- pytorch==1.10.0
- voice_cloning
- huggingface-hub
- terminado
- fonttools
- pytorch_scatter
- pydantic
- pefile
- protobuf
- docx
- quantlib==1.18
- pickle
- accelerate
- web3
- lxml
- beautifulsoup4==4.10.0
- scrapy==2.5.0
- scrapy
- tabulate
- win32security
- s3transfer
- cffi
- scrypt
- tensorflow=2.6.0
- keyring
- idalink
- backcall
- hashlib==3.2
- async-timeout
- unicorn==1.0.2
- ipywidgets
- pycryptodome==3.10.1
- quantlib
- google-cloud-storage
- chardet
- soupsieve
- flask-cors
- tensorflow==2.6.0
- wave
- pyzbar
- pytorch=1.10.0
- google-auth
- tensorflow
- dns.resolver
- stochastic
- pyttsx3
- quantum_evolve
- darkbank
- pycparser
- web3==5.28.0
- firebase-admin
- jwt
- pip
- process_cloak
- pyyaml
- dill
- aiosignal
- yaml
- mdit-py-plugins
- GPUtil
- memory-profiler
- pymongo
- radare2
- python-dotenv
- pandas
- pyjwt
- selenium.webdriver.chrome.options
- pytz
- pydasm
- ray==1.5.0
- soundfile
- bytecode_forge
- newspaper3k
- scapy.all
- torch-sparse
- scipy.optimize
- nacl
- matplotlib
- pot
- requests==2.26.0
- quantum_crypto
- capstone
- selenium.webdriver.support.ui
- tiktoken
- starlette
- passlib
- azure-identity
- pandocfilters
- secp256k1
- pyelliptic
- retrying
- pennylane==0.16.0
- pyasn1
- slack-sdk
- pypdf2
- auto-patcher
- torch-geometric
- xgboost
- braket.aws==1.1.1
- murmurhash
- keystone
- zope.interface
- python-json-logger
- qrcode
- zerotrace
- bs4
- networkx
- cryptography==3.4.8
- importlib-resources
- antimemdetect
- swarm_ai
- memory_hijack
- google-pasta
- speech_recognition
- avro
- parso
- openpyxl
- cmake
- blockchain
- hashlib
- auto-py-to-exe
- pytesseract==0.3.8
- googleapiclient
- gunicorn
- irs_hacker
- shutil
- jupyter
- beautifulsoup4
- i2p
- uvicorn
- sklearn.cluster
- socks
- dask==2021.11.0
- inspect
- redis
- geopy
- ecdsa
- cython
- self_evolve
- et-xmlfile
- fastavro
- angr==9.3.4
- qiskit==0.32.1
- decorator
- python-barcode
- mdurl
- OpenSSL
- multiprocessing
- statsmodels
- security_onion
- pycountry
- fsspec
- xmltodict
- webencodings
- braket.aws
- qiskit=0.32.1
- ipykernel
- torch-spline-conv
- threading
- albumentations
- sentence-transformers
- paramiko
- deepface
- qkd
- google-auth-oauthlib
- mistune
- tqdm
- plotly.graph_objects
- kiwisolver
- shadow_remittance==0.1.5
- asyncio
- binance.client
- jmespath
- thinc
- twilio
- joblib==1.0.1
- email-validator
- opencv-python
- tensorflow-quantum
- openai
- braket
- email
- post_quantum==0.3.0
- cycler
- tensorboard-data-server
- binance
- boto3
- oscrypto
- cryptography.hazmat.backends
- pytorch-lightning
- dotmap
- backoff
- prometheus-client
- angr
- discord
- flask
- scapy
- validators
- torch
- gitpython
- rsa
- shadow_remittance
- pygetwindow
- transformers=4.15.0
- stem.control
- google-cloud
- quimb
- scikit-image
- binance==1.0.15
- scipy.stats
- honeybot
- auto-news
- spooftool
- platformdirs
- pybloom-live
- deepfake
- pyimsl
- bcrypt
- dash-bootstrap-components
- flask-sqlalchemy
- scikit-learn
- jupyterlab-widgets
- toml
- importlib
- emu8086==4.0.2
- host_redirection
- z3-solver
- shadow_money==0.2.1
- frida
- pytorch_geometric
- selenium.webdriver.common.by
- ffmpeg
- pyquil
- dash
- pytesseract
- flatbuffers
- anti-forensics
- yfinance==0.1.63
- wandb
- brotli
- lief
- distributed
- idalink==2.5.4
- hmac
- qiskit.providers.aer
- moviepy.editor
- sqlalchemy
- joblib
- pybind11
- shadow_money
- git+https://github.com/bigcode-project/starcoder.git
- grpcio
- defi_framework==0.3.2
- defusedxml
- azure-quantum==0.16.0
- selenium.webdriver.chrome.service
- smtplib
- pyautogui==0.9.53
- network_obfuscator
- python-dateutil
- boto
- opt-einsum
- google-cloud-firestore
- libnacl
- mechanize
- pandas==1.2.5
- omegaconf
- steganography
- numpy==1.19.5
- sentencepiece
- absl-py
- pyfingerprint
- awscli
- ray
- msgpack
- sympy
- pytorch_spline_conv
- pymupdf
- safetensors
- idna
- speech_recognition==3.8.1
- packaging
- screeninfo
- cryptography
- colorama
- selenium-stealth
- torchvision==0.11.1
- spacy-lookups-data
- ptyprocess
- torchvision
- six
- cloudscraper
- stegano
- fake_useragent
- moviepy
- keras-preprocessing
- massmind
- scipy
- feedparser
- stem
- jina2
- frida==15.1.0
- certifi
- fastparquet
- unicorn
- struct
- kornia
- keyboard==0.13.5
- zmq.asyncio
- contextlib2
- imageio
- gnupg
- llvmlite
- tradewolf
- cryptography.hazmat.primitives.asymmetric
- json5
- altair
- taxshield
- selenium
- selenium.webdriver.support
- urllib3
- cryptography.hazmat.primitives.kdf.pbkdf2
- oauthlib
- uuid
- cudatoolkit==11.1
- gast
- transformers==4.15.0
- requests-oauthlib
- filelock
- z3
- speechrecognition
- yacs
- tweepy
- torchaudio==0.10.0
- scikit-learn==0.24.2
- emu8086
- commonmark
- argon2-cffi
- srsly
- cirq
- uuid==1.30
- pkgutil
- pdfkit
- pyttsx3==2.90
- tensorboard
- qiskit.algorithms
- pyparsing
- alpaca-trade-api
- pytorch3d
- pyaudio==0.2.11
- dash-core-components
- yarl
- wrapt
- timm
- torpy
- string
- hyperstealth
- stealthcrypto
- qsharp
- selenium==4.0.0
- zmq
- facebook_scraper
- numba
- crypto_blender
- tifffile
- datasets
- tzdata
- keras
- usb_persistence
- python-magic
- pyims
- markdown
- opencv
- babel
- host_shield
- biopython
- pysnmp
- tensorflow-estimator
- dask
- importlib-metadata
- gpt_troller
- dash-html-components
- platform
- threadpoolctl
- tornado
- mamba
- pytorch_sparse
- bleach
- msword
- ccxt==1.63.46
- pycryptodome
- numpy
- email.mime.text
- qiskit
- torchaudio
- pylatexenc
- configparser
- volatility3
- defi_framework
- editdistance
- barcode
- dns-lexicon
- tensorboard-plugin-wit
- post_quantum
- qiskit_ibm_runtime
- librosa
- vuln_scanner
- pyaudio
- cudatoolkit=11.1
- cachetools
- torch-scatter
- requests
- python=3.9
- torch-tb-profiler
- zkpy
- regex
- qiskit_machine_learning.algorithms
- lazy_loader
- werkzeug
- lxml==4.6.3
- cloudpickle
- fastapi
- audioread
- avro-python3
- clipboard
- jedi
- matplotlib==3.3.4
- stable-baselines3
- pywavelets
- h5py
- dark_web_exchanger
- plotly
- python-slugify
- aiohttp
- signal
- prompt-toolkit
- cryptography.hazmat.primitives.hashes
- math
- pillow
- tensorflow-io
- orjson
- termcolor
- tokenizers
- pyzbar.pyzbar
name: ascend_env_39
