name: Lint & Auto-Fix

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install flake8 and black
        run: |
          pip install flake8 black

      - name: Run flake8 (only judge)
        run: flake8 . --count --exit-zero --statistics

      - name: Auto-fix with black
        run: black .

      - name: Create Pull Request with fixes
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(style): auto-format code with black"
          title: "Auto-format code (judgment delivered)"
          body: "This PR was created by your friendly code janitor bot. It didn’t like what it saw."
          branch: bot/auto-format
