name: Lint, Fix & Review

on:
  workflow_run:
    workflows: ["AscendAI Validation & Lint"]
    types:
      - completed

jobs:
  full-cleanse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          pip install flake8 black bandit openai

      - name: Run Lint Check
        run: flake8 GremlinGPT/ --count --exit-zero --statistics

      - name: Auto-fix with Black
        run: black GremlinGPT/

      - name: Run Bandit Security Check
        run: bandit -r GremlinGPT/ -f txt -o bandit-report.txt

      - name: Run Smart Review AI Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/smart_review_agent.py

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: smart-reports
          path: |
            bandit-report.txt
            ai-review.json

      - name: Create Pull Request with Fixes
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(style): auto-format & review results"
          title: "Auto-format + AI Review"
          body: |
            This PR was generated by the AscendAI Validator Loop.
            Includes formatting fixes, security scan output, and GPT-based review suggestions.
          branch: bot/auto-fix-review
