name: GremlinGPT Validation & Lint

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Zsh
        run: sudo apt-get update && sudo apt-get install -y zsh

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          auto-activate-base: false

      - name: Debug environment
        shell: zsh {0}
        run: |
          echo "Conda at: $CONDA"
          ls -la $CONDA/bin
          conda --version

      - name: Create Conda environments
        shell: zsh {0}
        run: |
          cd GremlinGPT/conda_envs
          chmod +x create_envs.sh
          ./create_envs.sh

      - name: Install linters in gremlin-nlp
        shell: zsh {0}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate gremlin-nlp
          pip install flake8 black

      - name: Bootstrap NLP models
        shell: zsh {0}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate gremlin-nlp
          pip install transformers sentence-transformers
          python -c "from transformers import AutoTokenizer, AutoModel; AutoTokenizer.from_pretrained('bert-base-uncased'); AutoModel.from_pretrained('bert-base-uncased')"
          python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

      - name: Inject flake8 config (for Black compatibility)
        shell: zsh {0}
        run: |
          cat <<EOF > setup.cfg
          [flake8]
          max-line-length = 120
          exclude =
              __pycache__,
              .git,
              .venv,
              build,
              dist,
              GremlinGPT/data/prompts
          EOF

      - name: Run Black (auto-fix mode)
        shell: zsh {0}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate gremlin-nlp
          black GremlinGPT/ --line-length 120

      - name: Commit style fixes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: zsh {0}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate gremlin-nlp
          git config user.email "ci@gremlingpt.ai"
          git config user.name "GremlinBot"
          git add .
          git commit -m "style: auto-fix Black lint issues" || echo "No changes"
          git push || echo "Push not needed or not permitted"

      - name: Lint codebase
        shell: zsh {0}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate gremlin-nlp
          flake8 GremlinGPT/

      - name: Targeted Lint (fail on critical issues only)
        shell: zsh {0}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate gremlin-nlp
          flake8 GremlinGPT/ --count \
            --select=E9,F63,F7,F82 --show-source --statistics

- name: Run GremlinGPT
  shell: zsh {0}
  run: |
    conda activate gremlin-nlp
    cd GremlinGPT
    chmod +x start_all.sh
    ./start_all.sh || echo "Run complete, warnings ignored"
